// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

#include "employee.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace employee {

inline constexpr StatusReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : reply_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StatusReply::StatusReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StatusReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusReplyDefaultTypeInternal() {}
  union {
    StatusReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusReplyDefaultTypeInternal _StatusReply_default_instance_;

inline constexpr Setter::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Setter::Setter(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SetterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetterDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetterDefaultTypeInternal() {}
  union {
    Setter _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetterDefaultTypeInternal _Setter_default_instance_;

inline constexpr PostAndLead::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : post_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        lead_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PostAndLead::PostAndLead(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PostAndLeadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PostAndLeadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PostAndLeadDefaultTypeInternal() {}
  union {
    PostAndLead _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PostAndLeadDefaultTypeInternal _PostAndLead_default_instance_;

inline constexpr Id::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Id::Id(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct IdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IdDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IdDefaultTypeInternal() {}
  union {
    Id _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IdDefaultTypeInternal _Id_default_instance_;

inline constexpr GetListRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetListRequest::GetListRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetListRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetListRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetListRequestDefaultTypeInternal() {}
  union {
    GetListRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetListRequestDefaultTypeInternal _GetListRequest_default_instance_;

inline constexpr Employee::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        post_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        lead_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Employee::Employee(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct EmployeeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmployeeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmployeeDefaultTypeInternal() {}
  union {
    Employee _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmployeeDefaultTypeInternal _Employee_default_instance_;
}  // namespace employee
static ::_pb::Metadata file_level_metadata_employee_2eproto[6];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_employee_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_employee_2eproto = nullptr;
const ::uint32_t TableStruct_employee_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::employee::Employee, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::employee::Employee, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::employee::Employee, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::employee::Employee, _impl_.post_),
    PROTOBUF_FIELD_OFFSET(::employee::Employee, _impl_.lead_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::employee::GetListRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::employee::GetListRequest, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::employee::StatusReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::employee::StatusReply, _impl_.reply_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::employee::Id, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::employee::Id, _impl_.id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::employee::Setter, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::employee::Setter, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::employee::Setter, _impl_.data_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::employee::PostAndLead, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::employee::PostAndLead, _impl_.post_),
    PROTOBUF_FIELD_OFFSET(::employee::PostAndLead, _impl_.lead_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::employee::Employee)},
        {12, -1, -1, sizeof(::employee::GetListRequest)},
        {21, -1, -1, sizeof(::employee::StatusReply)},
        {30, -1, -1, sizeof(::employee::Id)},
        {39, -1, -1, sizeof(::employee::Setter)},
        {49, -1, -1, sizeof(::employee::PostAndLead)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::employee::_Employee_default_instance_._instance,
    &::employee::_GetListRequest_default_instance_._instance,
    &::employee::_StatusReply_default_instance_._instance,
    &::employee::_Id_default_instance_._instance,
    &::employee::_Setter_default_instance_._instance,
    &::employee::_PostAndLead_default_instance_._instance,
};
const char descriptor_table_protodef_employee_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016employee.proto\022\010employee\"@\n\010Employee\022\n"
    "\n\002ID\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004post\030\003 \001(\t\022\014"
    "\n\004lead\030\004 \001(\005\"\036\n\016GetListRequest\022\014\n\004name\030\001"
    " \001(\t\"\034\n\013StatusReply\022\r\n\005reply\030\001 \001(\t\"\020\n\002Id"
    "\022\n\n\002ID\030\001 \001(\005\"\"\n\006Setter\022\n\n\002ID\030\001 \001(\005\022\014\n\004da"
    "ta\030\002 \001(\t\")\n\013PostAndLead\022\014\n\004post\030\001 \001(\t\022\014\n"
    "\004lead\030\002 \001(\t2\366\002\n\nEmployeeDb\022=\n\016InsertEmpl"
    "oyee\022\022.employee.Employee\032\025.employee.Stat"
    "usReply\"\000\022;\n\007GetList\022\030.employee.GetListR"
    "equest\032\022.employee.Employee\"\0000\001\0227\n\016GetPos"
    "tAndLead\022\014.employee.Id\032\025.employee.PostAn"
    "dLead\"\000\022<\n\017SetEmployeePost\022\020.employee.Se"
    "tter\032\025.employee.StatusReply\"\000\022<\n\017SetEmpl"
    "oyeeLead\022\020.employee.Setter\032\025.employee.St"
    "atusReply\"\000\0227\n\016DeleteEmployee\022\014.employee"
    ".Id\032\025.employee.StatusReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_employee_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_employee_2eproto = {
    false,
    false,
    636,
    descriptor_table_protodef_employee_2eproto,
    "employee.proto",
    &descriptor_table_employee_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_employee_2eproto::offsets,
    file_level_metadata_employee_2eproto,
    file_level_enum_descriptors_employee_2eproto,
    file_level_service_descriptors_employee_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_employee_2eproto_getter() {
  return &descriptor_table_employee_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_employee_2eproto(&descriptor_table_employee_2eproto);
namespace employee {
// ===================================================================

class Employee::_Internal {
 public:
};

Employee::Employee(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:employee.Employee)
}
inline PROTOBUF_NDEBUG_INLINE Employee::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        post_(arena, from.post_),
        _cached_size_{0} {}

Employee::Employee(
    ::google::protobuf::Arena* arena,
    const Employee& from)
    : ::google::protobuf::Message(arena) {
  Employee* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, lead_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::lead_));

  // @@protoc_insertion_point(copy_constructor:employee.Employee)
}
inline PROTOBUF_NDEBUG_INLINE Employee::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        post_(arena),
        _cached_size_{0} {}

inline void Employee::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, lead_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::lead_));
}
Employee::~Employee() {
  // @@protoc_insertion_point(destructor:employee.Employee)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Employee::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.post_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Employee::Clear() {
// @@protoc_insertion_point(message_clear_start:employee.Employee)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.post_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.lead_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.lead_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Employee::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 34, 2> Employee::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Employee_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 lead = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Employee, _impl_.lead_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.lead_)}},
    // int32 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Employee, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.id_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.name_)}},
    // string post = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.post_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ID = 1;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string post = 3;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.post_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 lead = 4;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.lead_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\0\4\4\0\0\0\0"
    "employee.Employee"
    "name"
    "post"
  }},
};

::uint8_t* Employee::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:employee.Employee)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "employee.Employee.name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string post = 3;
  if (!this->_internal_post().empty()) {
    const std::string& _s = this->_internal_post();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "employee.Employee.post");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 lead = 4;
  if (this->_internal_lead() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_lead(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employee.Employee)
  return target;
}

::size_t Employee::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employee.Employee)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string post = 3;
  if (!this->_internal_post().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_post());
  }

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  // int32 lead = 4;
  if (this->_internal_lead() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_lead());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Employee::_class_data_ = {
    Employee::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Employee::GetClassData() const {
  return &_class_data_;
}

void Employee::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Employee*>(&to_msg);
  auto& from = static_cast<const Employee&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:employee.Employee)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_post().empty()) {
    _this->_internal_set_post(from._internal_post());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_lead() != 0) {
    _this->_internal_set_lead(from._internal_lead());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Employee::CopyFrom(const Employee& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employee.Employee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Employee::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Employee::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Employee::InternalSwap(Employee* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.post_, &other->_impl_.post_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Employee, _impl_.lead_)
      + sizeof(Employee::_impl_.lead_)
      - PROTOBUF_FIELD_OFFSET(Employee, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Employee::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_employee_2eproto_getter, &descriptor_table_employee_2eproto_once,
      file_level_metadata_employee_2eproto[0]);
}
// ===================================================================

class GetListRequest::_Internal {
 public:
};

GetListRequest::GetListRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:employee.GetListRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetListRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

GetListRequest::GetListRequest(
    ::google::protobuf::Arena* arena,
    const GetListRequest& from)
    : ::google::protobuf::Message(arena) {
  GetListRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:employee.GetListRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetListRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void GetListRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetListRequest::~GetListRequest() {
  // @@protoc_insertion_point(destructor:employee.GetListRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetListRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GetListRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:employee.GetListRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetListRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2> GetListRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetListRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetListRequest, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(GetListRequest, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\4\0\0\0\0\0\0"
    "employee.GetListRequest"
    "name"
  }},
};

::uint8_t* GetListRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:employee.GetListRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "employee.GetListRequest.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employee.GetListRequest)
  return target;
}

::size_t GetListRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employee.GetListRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GetListRequest::_class_data_ = {
    GetListRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GetListRequest::GetClassData() const {
  return &_class_data_;
}

void GetListRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GetListRequest*>(&to_msg);
  auto& from = static_cast<const GetListRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:employee.GetListRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetListRequest::CopyFrom(const GetListRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employee.GetListRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetListRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GetListRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GetListRequest::InternalSwap(GetListRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata GetListRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_employee_2eproto_getter, &descriptor_table_employee_2eproto_once,
      file_level_metadata_employee_2eproto[1]);
}
// ===================================================================

class StatusReply::_Internal {
 public:
};

StatusReply::StatusReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:employee.StatusReply)
}
inline PROTOBUF_NDEBUG_INLINE StatusReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : reply_(arena, from.reply_),
        _cached_size_{0} {}

StatusReply::StatusReply(
    ::google::protobuf::Arena* arena,
    const StatusReply& from)
    : ::google::protobuf::Message(arena) {
  StatusReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:employee.StatusReply)
}
inline PROTOBUF_NDEBUG_INLINE StatusReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : reply_(arena),
        _cached_size_{0} {}

inline void StatusReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
StatusReply::~StatusReply() {
  // @@protoc_insertion_point(destructor:employee.StatusReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StatusReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.reply_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void StatusReply::Clear() {
// @@protoc_insertion_point(message_clear_start:employee.StatusReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reply_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* StatusReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> StatusReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_StatusReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string reply = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StatusReply, _impl_.reply_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string reply = 1;
    {PROTOBUF_FIELD_OFFSET(StatusReply, _impl_.reply_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\5\0\0\0\0\0\0"
    "employee.StatusReply"
    "reply"
  }},
};

::uint8_t* StatusReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:employee.StatusReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string reply = 1;
  if (!this->_internal_reply().empty()) {
    const std::string& _s = this->_internal_reply();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "employee.StatusReply.reply");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employee.StatusReply)
  return target;
}

::size_t StatusReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employee.StatusReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reply = 1;
  if (!this->_internal_reply().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_reply());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData StatusReply::_class_data_ = {
    StatusReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* StatusReply::GetClassData() const {
  return &_class_data_;
}

void StatusReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<StatusReply*>(&to_msg);
  auto& from = static_cast<const StatusReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:employee.StatusReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reply().empty()) {
    _this->_internal_set_reply(from._internal_reply());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StatusReply::CopyFrom(const StatusReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employee.StatusReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool StatusReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* StatusReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void StatusReply::InternalSwap(StatusReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reply_, &other->_impl_.reply_, arena);
}

::google::protobuf::Metadata StatusReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_employee_2eproto_getter, &descriptor_table_employee_2eproto_once,
      file_level_metadata_employee_2eproto[2]);
}
// ===================================================================

class Id::_Internal {
 public:
};

Id::Id(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:employee.Id)
}
Id::Id(
    ::google::protobuf::Arena* arena, const Id& from)
    : Id(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Id::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Id::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Id::~Id() {
  // @@protoc_insertion_point(destructor:employee.Id)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Id::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Id::Clear() {
// @@protoc_insertion_point(message_clear_start:employee.Id)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Id::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> Id::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Id_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Id, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Id, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ID = 1;
    {PROTOBUF_FIELD_OFFSET(Id, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Id::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:employee.Id)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employee.Id)
  return target;
}

::size_t Id::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employee.Id)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Id::_class_data_ = {
    Id::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Id::GetClassData() const {
  return &_class_data_;
}

void Id::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Id*>(&to_msg);
  auto& from = static_cast<const Id&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:employee.Id)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Id::CopyFrom(const Id& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employee.Id)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Id::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Id::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Id::InternalSwap(Id* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Id::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_employee_2eproto_getter, &descriptor_table_employee_2eproto_once,
      file_level_metadata_employee_2eproto[3]);
}
// ===================================================================

class Setter::_Internal {
 public:
};

Setter::Setter(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:employee.Setter)
}
inline PROTOBUF_NDEBUG_INLINE Setter::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : data_(arena, from.data_),
        _cached_size_{0} {}

Setter::Setter(
    ::google::protobuf::Arena* arena,
    const Setter& from)
    : ::google::protobuf::Message(arena) {
  Setter* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:employee.Setter)
}
inline PROTOBUF_NDEBUG_INLINE Setter::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_(arena),
        _cached_size_{0} {}

inline void Setter::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Setter::~Setter() {
  // @@protoc_insertion_point(destructor:employee.Setter)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Setter::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Setter::Clear() {
// @@protoc_insertion_point(message_clear_start:employee.Setter)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Setter::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 28, 2> Setter::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Setter_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string data = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Setter, _impl_.data_)}},
    // int32 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Setter, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Setter, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ID = 1;
    {PROTOBUF_FIELD_OFFSET(Setter, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string data = 2;
    {PROTOBUF_FIELD_OFFSET(Setter, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\0\4\0\0\0\0\0"
    "employee.Setter"
    "data"
  }},
};

::uint8_t* Setter::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:employee.Setter)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string data = 2;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "employee.Setter.data");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employee.Setter)
  return target;
}

::size_t Setter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employee.Setter)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string data = 2;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_data());
  }

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Setter::_class_data_ = {
    Setter::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Setter::GetClassData() const {
  return &_class_data_;
}

void Setter::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Setter*>(&to_msg);
  auto& from = static_cast<const Setter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:employee.Setter)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Setter::CopyFrom(const Setter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employee.Setter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Setter::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Setter::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Setter::InternalSwap(Setter* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Setter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_employee_2eproto_getter, &descriptor_table_employee_2eproto_once,
      file_level_metadata_employee_2eproto[4]);
}
// ===================================================================

class PostAndLead::_Internal {
 public:
};

PostAndLead::PostAndLead(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:employee.PostAndLead)
}
inline PROTOBUF_NDEBUG_INLINE PostAndLead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : post_(arena, from.post_),
        lead_(arena, from.lead_),
        _cached_size_{0} {}

PostAndLead::PostAndLead(
    ::google::protobuf::Arena* arena,
    const PostAndLead& from)
    : ::google::protobuf::Message(arena) {
  PostAndLead* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:employee.PostAndLead)
}
inline PROTOBUF_NDEBUG_INLINE PostAndLead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : post_(arena),
        lead_(arena),
        _cached_size_{0} {}

inline void PostAndLead::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PostAndLead::~PostAndLead() {
  // @@protoc_insertion_point(destructor:employee.PostAndLead)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PostAndLead::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.post_.Destroy();
  _impl_.lead_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PostAndLead::Clear() {
// @@protoc_insertion_point(message_clear_start:employee.PostAndLead)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.post_.ClearToEmpty();
  _impl_.lead_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PostAndLead::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 37, 2> PostAndLead::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PostAndLead_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string lead = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PostAndLead, _impl_.lead_)}},
    // string post = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PostAndLead, _impl_.post_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string post = 1;
    {PROTOBUF_FIELD_OFFSET(PostAndLead, _impl_.post_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string lead = 2;
    {PROTOBUF_FIELD_OFFSET(PostAndLead, _impl_.lead_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\4\4\0\0\0\0\0"
    "employee.PostAndLead"
    "post"
    "lead"
  }},
};

::uint8_t* PostAndLead::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:employee.PostAndLead)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string post = 1;
  if (!this->_internal_post().empty()) {
    const std::string& _s = this->_internal_post();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "employee.PostAndLead.post");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string lead = 2;
  if (!this->_internal_lead().empty()) {
    const std::string& _s = this->_internal_lead();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "employee.PostAndLead.lead");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employee.PostAndLead)
  return target;
}

::size_t PostAndLead::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employee.PostAndLead)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string post = 1;
  if (!this->_internal_post().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_post());
  }

  // string lead = 2;
  if (!this->_internal_lead().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_lead());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PostAndLead::_class_data_ = {
    PostAndLead::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PostAndLead::GetClassData() const {
  return &_class_data_;
}

void PostAndLead::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PostAndLead*>(&to_msg);
  auto& from = static_cast<const PostAndLead&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:employee.PostAndLead)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_post().empty()) {
    _this->_internal_set_post(from._internal_post());
  }
  if (!from._internal_lead().empty()) {
    _this->_internal_set_lead(from._internal_lead());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PostAndLead::CopyFrom(const PostAndLead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employee.PostAndLead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PostAndLead::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PostAndLead::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PostAndLead::InternalSwap(PostAndLead* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.post_, &other->_impl_.post_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.lead_, &other->_impl_.lead_, arena);
}

::google::protobuf::Metadata PostAndLead::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_employee_2eproto_getter, &descriptor_table_employee_2eproto_once,
      file_level_metadata_employee_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace employee
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
