# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x12\x08\x65mployee\"@\n\x08\x45mployee\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04post\x18\x03 \x01(\t\x12\x0c\n\x04lead\x18\x04 \x01(\x05\"E\n\rEmployeeReply\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04post\x18\x03 \x01(\t\x12\x0c\n\x04lead\x18\x04 \x01(\t\"\x1e\n\x0eGetListRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0bStatusReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\x10\n\x02Id\x12\n\n\x02ID\x18\x01 \x01(\x05\"\'\n\x0bPost_Setter\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\'\n\x0bLead_Setter\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x05\")\n\x0bPostAndLead\x12\x0c\n\x04post\x18\x01 \x01(\t\x12\x0c\n\x04lead\x18\x02 \x01(\t2\x85\x03\n\nEmployeeDb\x12=\n\x0eInsertEmployee\x12\x12.employee.Employee\x1a\x15.employee.StatusReply\"\x00\x12@\n\x07GetList\x12\x18.employee.GetListRequest\x1a\x17.employee.EmployeeReply\"\x00\x30\x01\x12\x37\n\x0eGetPostAndLead\x12\x0c.employee.Id\x1a\x15.employee.PostAndLead\"\x00\x12\x41\n\x0fSetEmployeePost\x12\x15.employee.Post_Setter\x1a\x15.employee.StatusReply\"\x00\x12\x41\n\x0fSetEmployeeLead\x12\x15.employee.Lead_Setter\x1a\x15.employee.StatusReply\"\x00\x12\x37\n\x0e\x44\x65leteEmployee\x12\x0c.employee.Id\x1a\x15.employee.StatusReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPLOYEE']._serialized_start=28
  _globals['_EMPLOYEE']._serialized_end=92
  _globals['_EMPLOYEEREPLY']._serialized_start=94
  _globals['_EMPLOYEEREPLY']._serialized_end=163
  _globals['_GETLISTREQUEST']._serialized_start=165
  _globals['_GETLISTREQUEST']._serialized_end=195
  _globals['_STATUSREPLY']._serialized_start=197
  _globals['_STATUSREPLY']._serialized_end=225
  _globals['_ID']._serialized_start=227
  _globals['_ID']._serialized_end=243
  _globals['_POST_SETTER']._serialized_start=245
  _globals['_POST_SETTER']._serialized_end=284
  _globals['_LEAD_SETTER']._serialized_start=286
  _globals['_LEAD_SETTER']._serialized_end=325
  _globals['_POSTANDLEAD']._serialized_start=327
  _globals['_POSTANDLEAD']._serialized_end=368
  _globals['_EMPLOYEEDB']._serialized_start=371
  _globals['_EMPLOYEEDB']._serialized_end=760
# @@protoc_insertion_point(module_scope)
